### ISSUE TITLE
NoMethodError (undefined method `head' for nil:NilClass):

### ISSUE THREAD

**Issue by radialflux** [drcapulet/warehouse#1]
I followed the instructions and started the application - i get NoMethodError (undefined method `head' for nil:NilClass):  any thoughts on what i did wrong?

**Comment by drcapulet** [comment]
Did you add a repository?

**Comment by radialflux** [comment]
I cannot get to the point to add a repo - could you give me a hint?  I went to 0.0.0.0:3000 and just get a blank page regardless of the enviroment (actuall in production I get the std 500)

**Comment by radialflux** [comment]
Actually, I get this:  

Unknown action

No action responded to index. Actions:

**Comment by drcapulet** [comment]
Thats because the app is not finished yet. I haven't gotten to that yet. Go to /repositories/new to create one and then you can sync and visit.

**Comment by radialflux** [comment]
ah, ok - thanks!
