### ISSUE TITLE
Can't start :(

### ISSUE THREAD

**Issue by rlex** [drcapulet/warehouse#3]
Installed by instruction, tryin' to start it. But with passenger i get nothing (just infinity load) and with webrick...
gitmaster@ps12894:~/git.x-demon.org 0_o $ ruby script/server 
=> Booting WEBrick
=> Rails 2.3.5 application starting on http://0.0.0.0:3000
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/gem_dependency.rb:119:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2010-05-15 23:23:35] INFO  WEBrick 1.3.1
[2010-05-15 23:23:35] INFO  ruby 1.8.7 (2009-12-24) [x86_64-linux]
[2010-05-15 23:23:35] INFO  WEBrick::HTTPServer#start: pid=31302 port=3000

Processing ApplicationController#index (for 95.165.187.253 at 2010-05-15 23:23:52) [GET]

ActionController::UnknownAction (No action responded to index. Actions: ):
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:617:in `call_filters'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:610:in`perform_action_without_benchmark'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/flash.rb:146:in`perform_action'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in `send'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in`process_without_filters'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:606:in `process_without_compass'
  compass (0.8.17) lib/compass/app_integration/rails/action_controller.rb:7:in`process'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:391:in `process'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:386:in`call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:437:in `call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:87:in`dispatch'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:121:in `_call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:130
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:29:in`call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:29:in `call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in`cache'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:9:in `cache'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:28:in`call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
  haml (3.0.4) lib/sass/plugin/rack.rb:41:in`call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/string_coercion.rb:25:in `call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/params_parser.rb:15:in`call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/session/cookie_store.rb:93:in `call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/failsafe.rb:26:in`call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:114:in `call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/reloader.rb:34:in`run'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:108:in `call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/rack/static.rb:31:in`call'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/rack/log_tailer.rb:17:in `call'
  /opt/ruby-enterprise/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
  /opt/ruby-enterprise/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
  /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
  /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:95:in `start'
  /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:92:in`each'
  /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:92:in `start'
  /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:23:in`start'
  /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:82:in `start'
  /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/commands/server.rb:111

Rendering rescues/layout (not_found)
I have ~10 repositories in ~/repositories/ (all is bare repos, left from gitolite installation)

**Comment by drcapulet** [comment]
Did you already add any of them to the database?

**Comment by rlex** [comment]
you mean warehouse:sync? Yes, i added it.

**Comment by drcapulet** [comment]
Well if they are added to the db, head to /repositories if you are using the latest version and that should work

**Comment by rlex** [comment]
Looks like i can't add them. Went to /repositories (via WEBrick - passenger does not start) and i saw that there is no repos. When tried adding existing one, it fails - saying "Repository couldn't be created"
Warehouse is in /home/gitmaster/git.x-demon.org
Git repos is in /home/gitmaster/repositories/%NAME%.git

Part of log from webrick:

Processing RepositoriesController#create (for 95.165.187.253 at 2010-05-16 00:17:48) [POST]
  Parameters: {"repository"=>{"name"=>"pkgbuilds", "path"=>"/home/gitmaster/repositories/xdemon-pkgbuilds.git/"}, "commit"=>"Create Repository", "authenticity_token"=>"602Ju3IW6qTEi+yiV3NKZIu3RKDrurUG9HT80DneEH8="}
Rendering template within layouts/application
Rendering repositories/new
Completed in 11ms (View: 9, DB: 0) | 200 OK [http://lex.gs/repositories](xdemon-pkgbuilds.git exists)

**Comment by drcapulet** [comment]
Found the culprit. Checkout the latest version and that should fix it. :)

**Comment by rlex** [comment]
Yeah, fixed. I think our company will fork it (of course with publishing sources) if You not against it.

**Comment by drcapulet** [comment]
Not at all :) I'd love to see what you want to add - maybe even add it into the main branch!

**Comment by rlex** [comment]
Auth, users management (ssh/users) - to replace gitolite/gitosis, forking, per-branch permissions (probably)
