### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by rlex** [drcapulet/warehouse#4]
When i'm tryin to sync repos, i get following error:

gitmaster@ps12894:~/git.x-demon.org ^_^ $ RAILS_ENV=production /opt/ruby-enterprise/bin/rake warehouse:sync --trace
(in /home/gitmaster/git.x-demon.org)
*\* Invoke warehouse:sync (first_time)
*\* Execute warehouse:sync
pkgbuilds
rake aborted!  100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| ETA:  00:00:00
undefined local variable or method `root_url' for #<Warehouse::Syncer:0x3e0b2c8>
/home/gitmaster/git.x-demon.org/lib/warehouse/syncer.rb:131:in`create_payload_for_hooks'
/home/gitmaster/git.x-demon.org/lib/warehouse/syncer.rb:118:in `each'
/home/gitmaster/git.x-demon.org/lib/warehouse/syncer.rb:118:in`create_payload_for_hooks'
/home/gitmaster/git.x-demon.org/lib/warehouse/syncer.rb:80:in `process'
/home/gitmaster/git.x-demon.org/lib/warehouse/syncer.rb:41:in`each'
/home/gitmaster/git.x-demon.org/lib/warehouse/syncer.rb:41:in `process'
/home/gitmaster/git.x-demon.org/lib/warehouse/syncer.rb:31:in`process'
./app/models/repository.rb:26:in `sync_revisions'
/home/gitmaster/git.x-demon.org/lib/warehouse/syncer.rb:33:in`process'
/home/gitmaster/git.x-demon.org/lib/warehouse/syncer.rb:33:in `each'
/home/gitmaster/git.x-demon.org/lib/warehouse/syncer.rb:33:in`process'
/home/gitmaster/git.x-demon.org/lib/tasks/syncer.rake:7
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/opt/ruby-enterprise/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/opt/ruby-enterprise/bin/rake:19:in`load'
/opt/ruby-enterprise/bin/rake:19

And if i sync for second / third / etc time, i got x2 / x3 / etc commits in my webinterface.
Is it just some sort of pre-fetch or this should be run on every repo update?

**Comment by rlex** [comment]
i believe that there is no write to some SQL table. Something like synced = 1

**Comment by drcapulet** [comment]
Fix sync problem. Closed by 8934e3e33ad80967a635521068f1621a3d17689a
