### ISSUE TITLE
Cannot sync for the first time.

### ISSUE THREAD

**Issue by dannymcc** [drcapulet/warehouse#6]
I tried to run the sync command after adding a repo. I get the following error:

macbook:warehouse danny$ rake warehouse:sync
(in /Users/danny/Dropbox/SVN/railsapps/warehouse)
Survey Manager
The syncer had a problem syncing, try changing the git timeout in warehouse.yml. It tried to run:
0

I changed the timeout in warehouse.yml from 60 to 600 but got the same error.

The dashboard seems to show the last details:

Survey Managerlatest commit: 32c27852dd43b85e47a6f2d09642fc9221e9f817 needs to be synced

but that's all.

Thanks,

Danny

**Comment by drcapulet** [comment]
You just need to increase the timeout until the error goes away. Grit (the ruby git library) seems to very slow at large commits while the command line is much faster and others Grit is much faster than the command line. It just depends. A commit once took ten minutes to import for me, so I'd recommend a time of around an hour just to be on the safe side.
