### ISSUE TITLE
initial host/repo config & warehouse.yml

### ISSUE THREAD

**Issue by mistcat** [drcapulet/warehouse#8]
When I try to run warehouse with the defaults in wrehouse.yml I get this error from passenger:
Error message:
    private method `gsub' called for nil:NilClass
Exception class:
    NoMethodError
Application root:
    /var/www/warehouse 

I tried replacing the host lines with my own domainname, but no dice.  I think I must just be missing some important configuration element here, but I can't figure it out.  Is Warehouse.yml even what I should be messing with?

Thanks!
Nate

**Comment by mistcat** [comment]
backtrace here:
Backtrace:
    #   File    Line    Location
    0   /var/www/warehouse/app/models/notifier.rb   2  
    1   /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb    158     in `require'
    2   /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb    158     in`require'
    3   /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb    265     in `require_or_load'
    4   /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb    224     in`depend_on'
    5   /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb    136     in `require_dependency'
    6   /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb    414     in`load_application_classes'
    7   /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb    413     in `each'
    8   /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb    413     in`load_application_classes'
    9   /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb    411     in `each'
    10  /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb    411     in`load_application_classes'
    11  /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb    197     in `process'
    12  /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb    113     in`send'
    13  /opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb    113     in `run'
    14  /var/www/warehouse/config/environment.rb    9   
    15  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb    318     in`require'
    16  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb    318     in `preload_application'
    17  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb    267     in`initialize_server'
    18  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/utils.rb    323     in `report_app_init_status'
    19  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb    246     in`initialize_server'
    20  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb  194     in `start_synchronously'
    21  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb  163     in`start'
    22  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb    222     in `start'
    23  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb    253     in`spawn_rails_application'
    24  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server_collection.rb   126     in `lookup_or_add'
    25  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb    247     in`spawn_rails_application'
    26  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server_collection.rb   80  in `synchronize'
    27  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server_collection.rb   79  in`synchronize'
    28  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb    246     in `spawn_rails_application'
    29  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb    145     in`spawn_application'
    30  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb    278     in `handle_spawn_application'
    31  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb  352     in`**send**'
    32  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb  352     in `main_loop'
    33  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb  196     in`start_synchronously'
    34  /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/bin/passenger-spawn-server    61

**Comment by drcapulet** [comment]
Could you paste your warehouse.yml file please? And yes that is the file you should be messing with :)

**Comment by mistcat** [comment]
# Warehouse

# \- host: for the syncer b/c it doesn't load a full Rail env

# \- commits_whenever: if the repo isn't synced all the way back, this will do a file access lookup, degrades performance

development:
  host: http://git.tigglobal.comt:80
  commits_whenever: false
  git_timeout: 60
  log_syncer: true

production:
  host: http://git.tigglobal.com:80 
  commits_whenever: false
  git_timeout: 60

Thanks for your help!

**Comment by mistcat** [comment]
(minus that extra t in the dev one, copy/paste error)

**Comment by mistcat** [comment]
a look in the production error log reveals this:
Processing UserSessionsController#new (for 128.62.55.154 at 2010-10-14 15:19:08) [GET]
  Parameters: {"action"=>"new", "controller"=>"user_sessions"}
Rendering template within layouts/login
Rendering user_sessions/new

ActionView::TemplateError (undefined method `login' for #<UserSession: no credentials provided>) on line #3 of app/views/user_sessions/new.html.erb:
1: <% semantic_form_for @user_session, :url => login_path do |form| -%>
2:  <% form.inputs do -%>
3:      <%= form.inputs :login, :password  %>
4:      <%= form.input :remember_me, :as => :boolean %>
5:  <% end -%>
6:  <% form.buttons do %>

```
formtastic (0.9.8) rails/./lib/formtastic.rb:571:in `send'
formtastic (0.9.8) rails/./lib/formtastic.rb:571:in `basic_input_helper'
formtastic (0.9.8) rails/./lib/formtastic.rb:576:in `string_input'
formtastic (0.9.8) rails/./lib/formtastic.rb:1186:in `send'
formtastic (0.9.8) rails/./lib/formtastic.rb:1186:in `inline_input_for'
lib/warehouse_form_builder.rb:30:in `send'
lib/warehouse_form_builder.rb:30:in `input'
lib/warehouse_form_builder.rb:29:in `map'
lib/warehouse_form_builder.rb:29:in `input'
formtastic (0.9.8) rails/./lib/formtastic.rb:275:in `inputs'
formtastic (0.9.8) rails/./lib/formtastic.rb:275:in `collect'
formtastic (0.9.8) rails/./lib/formtastic.rb:275:in `inputs'
app/views/user_sessions/new.html.erb:3
haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:92:in `capture'
formtastic (0.9.8) rails/./lib/formtastic.rb:1269:in `field_set_and_list_wrapping'
formtastic (0.9.8) rails/./lib/formtastic.rb:266:in `inputs'
app/views/user_sessions/new.html.erb:2
haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:235:in `form_for'
formtastic (0.9.8) rails/./lib/formtastic.rb:1703:in `semantic_form_for'
formtastic (0.9.8) rails/./lib/formtastic.rb:1681:in `with_custom_field_error_proc'
formtastic (0.9.8) rails/./lib/formtastic.rb:1702:in `semantic_form_for'
app/views/user_sessions/new.html.erb:1
haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:13:in `render'
haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:13:in `render'
compass (0.8.17) lib/compass/app_integration/rails/action_controller.rb:7:in `process'
haml (3.0.17) lib/sass/plugin/rack.rb:41:in `call'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:441:in `start_request_handler'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:381:in `handle_spawn_application'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/utils.rb:252:in `safe_fork'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:377:in `handle_spawn_application'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:163:in `start'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:222:in `start'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:253:in `spawn_rails_application'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:247:in `spawn_rails_application'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:246:in `spawn_rails_application'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:145:in `spawn_application'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:278:in `handle_spawn_application'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
```

**Comment by drcapulet** [comment]
The second one was me :P have you tried booting up the console?

**Comment by mistcat** [comment]
I haven't, what should I try and run from there?

**Comment by mistcat** [comment]
I see in there something about "no credentials" having been provided, do I need to give it a git user/pass somewhere?

**Comment by mistcat** [comment]
console output:

> > WH_CONFIG
> > => {:log_syncer=>true, :commits_whenever=>false, :git_timeout=>60, :host=>"http://git.tigglobal.com:80"}

**Comment by mistcat** [comment]
as for the credentials thing, I see an error related in that when it tries to create a new user session, maybe on initial page load?

Processing UserSessionsController#new (for 205.201.251.67 at 2010-10-14 17:20:25) [GET]
  Parameters: {"action"=>"new", "controller"=>"user_sessions"}
Rendering template within layouts/login
Rendering user_sessions/new

ActionView::TemplateError (undefined method `login' for #<UserSession: no credentials provided>) on line #3 of app/views/user_sessions/new.html.erb:
1: <% semantic_form_for @user_session, :url => login_path do |form| -%>
2:      <% form.inputs do -%>
3:              <%= form.inputs :login, :password  %>
4:              <%= form.input :remember_me, :as => :boolean %>
5:      <% end -%>
6:      <% form.buttons do %>

```
formtastic (0.9.8) rails/./lib/formtastic.rb:571:in `send'
formtastic (0.9.8) rails/./lib/formtastic.rb:571:in `basic_input_helper'
formtastic (0.9.8) rails/./lib/formtastic.rb:576:in `string_input'
formtastic (0.9.8) rails/./lib/formtastic.rb:1186:in `send'
formtastic (0.9.8) rails/./lib/formtastic.rb:1186:in `inline_input_for'
lib/warehouse_form_builder.rb:30:in `send'
lib/warehouse_form_builder.rb:30:in `input'
lib/warehouse_form_builder.rb:29:in `map'
lib/warehouse_form_builder.rb:29:in `input'
formtastic (0.9.8) rails/./lib/formtastic.rb:275:in `inputs'
formtastic (0.9.8) rails/./lib/formtastic.rb:275:in `collect'
formtastic (0.9.8) rails/./lib/formtastic.rb:275:in `inputs'
app/views/user_sessions/new.html.erb:3
haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:92:in `capture'
formtastic (0.9.8) rails/./lib/formtastic.rb:1269:in `field_set_and_list_wrapping'
formtastic (0.9.8) rails/./lib/formtastic.rb:266:in `inputs'
app/views/user_sessions/new.html.erb:2
haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:235:in `form_for'
formtastic (0.9.8) rails/./lib/formtastic.rb:1703:in `semantic_form_for'
formtastic (0.9.8) rails/./lib/formtastic.rb:1681:in `with_custom_field_error_proc'
formtastic (0.9.8) rails/./lib/formtastic.rb:1702:in `semantic_form_for'
app/views/user_sessions/new.html.erb:1
haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:13:in `render'
haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:13:in `render'
compass (0.8.17) lib/compass/app_integration/rails/action_controller.rb:7:in `process'
haml (3.0.17) lib/sass/plugin/rack.rb:41:in `call'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:441:in `start_request_handler'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:381:in `handle_spawn_application'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/utils.rb:252:in `safe_fork'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:377:in `handle_spawn_application'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:163:in `start'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:222:in `start'
/opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:253:in `spawn_rails_application'
```

**Comment by drcapulet** [comment]
Looking at your console output, it is puzzling why you receive the error at the beginning. What happens when you try WH_CONFIG[:host]?

**Comment by mistcat** [comment]
> > WH_CONFIG[:host]
> > => "http://git.tigglobal.com:80"

could there be some version or library issue with it thinking that there should be a "login" method in the user_sessions controller?  Or is that just a red-herring that's just a symptom of something else?

**Comment by drcapulet** [comment]
What environment are you trying to run the server in?

**Comment by mistcat** [comment]
RHEL 5.5 w/Enterprise Ruby 1.87 & Passenger 2.2.15

**Comment by drcapulet** [comment]
But production though, correct? and I shot you an email to the one listed on your github profile :)

**Comment by mistcat** [comment]
word, production, I'll check it out! Thanks for your help with this!

**Comment by MACRASSI** [comment]
Help! I have the same problem.

Getting this too:

Processing DashboardController#index (for 10.0.1.6 at 2010-10-22 22:41:26) [GET]
  Parameters: {"action"=>"index", "controller"=>"dashboard"}
Redirected to http://10.0.1.3:4710/login
Filter chain halted as [:login_required] rendered_or_redirected.
Completed in 6ms (DB: 0) | 302 Found [http://10.0.1.3/]

Processing UserSessionsController#new (for 10.0.1.6 at 2010-10-22 22:41:26) [GET]
  Parameters: {"action"=>"new", "controller"=>"user_sessions"}
Rendering template within layouts/login
Rendering user_sessions/new

ActionView::TemplateError (undefined method `login' for #<UserSession: no credentials provided>) on line #3 of app/views/user_sessions/new.html.erb:
1: <% semantic_form_for @user_session, :url => login_path do |form| -%>
2:  <% form.inputs do -%>
3:      <%= form.inputs :login, :password  %>
4:      <%= form.input :remember_me, :as => :boolean %>
5:  <% end -%>
6:  <% form.buttons do %>

formtastic (0.9.8) rails/./lib/formtastic.rb:571:in `send'
    formtastic (0.9.8) rails/./lib/formtastic.rb:571:in`basic_input_helper'
    formtastic (0.9.8) rails/./lib/formtastic.rb:576:in `string_input'
    formtastic (0.9.8) rails/./lib/formtastic.rb:1186:in`send'
    formtastic (0.9.8) rails/./lib/formtastic.rb:1186:in `inline_input_for'
    lib/warehouse_form_builder.rb:30:in`send'
    lib/warehouse_form_builder.rb:30:in `input'
    lib/warehouse_form_builder.rb:29:in`map'
    lib/warehouse_form_builder.rb:29:in `input'
    formtastic (0.9.8) rails/./lib/formtastic.rb:275:in`inputs'
    formtastic (0.9.8) rails/./lib/formtastic.rb:275:in `collect'
    formtastic (0.9.8) rails/./lib/formtastic.rb:275:in`inputs'
    app/views/user_sessions/new.html.erb:3
    haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:92:in `capture'
    formtastic (0.9.8) rails/./lib/formtastic.rb:1269:in`field_set_and_list_wrapping'
    formtastic (0.9.8) rails/./lib/formtastic.rb:266:in `inputs'
    app/views/user_sessions/new.html.erb:2
    haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:235:in`form_for'
    formtastic (0.9.8) rails/./lib/formtastic.rb:1703:in `semantic_form_for'
    formtastic (0.9.8) rails/./lib/formtastic.rb:1681:in`with_custom_field_error_proc'
    formtastic (0.9.8) rails/./lib/formtastic.rb:1702:in `semantic_form_for'
    app/views/user_sessions/new.html.erb:1
    haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:13:in`render'
    haml (3.0.17) rails/./lib/haml/helpers/action_view_mods.rb:13:in `render'
    compass (0.8.17) lib/compass/app_integration/rails/action_controller.rb:7:in`process'
    haml (3.0.17) lib/sass/plugin/rack.rb:41:in `call'
    /usr/lib/ruby/1.8/rack/head.rb:9:in`call'
    /usr/lib/ruby/1.8/rack/methodoverride.rb:24:in `call'
    /usr/lib/ruby/1.8/rack/lock.rb:11:in`call'
    /usr/lib/ruby/1.8/rack/lock.rb:11:in `synchronize'
    /usr/lib/ruby/1.8/rack/lock.rb:11:in`call'
    /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:92:in `process_request'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in`main_loop'
    /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:441:in `start_request_handler'
    /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:381:in`handle_spawn_application'
    /usr/lib/ruby/1.8/phusion_passenger/utils.rb:252:in `safe_fork'
    /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:377:in`handle_spawn_application'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in`main_loop'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in`start'
    /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:222:in `start'
    /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:253:in`spawn_rails_application'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
    /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:247:in`spawn_rails_application'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in`synchronize'
    /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:246:in `spawn_rails_application'
    /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:145:in`spawn_application'
    /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:278:in `handle_spawn_application'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in`**send**'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in`start_synchronously'
    /usr/lib/phusion_passenger/passenger-spawn-server:61

Any idea?

**Comment by MACRASSI** [comment]
I don't know why but now it works. :D
Hurray :D
