### ISSUE TITLE
sync problem

### ISSUE THREAD

**Issue by MACRASSI** [drcapulet/warehouse#9]
when i try to sync i get this error.

DEPRECATION WARNING: require "activeresource" is deprecated and will be removed in Rails 3. Use require "active_resource" instead.. (called from /var/lib/gems/1.8/gems/activeresource-2.3.5/lib/activeresource.rb:2)
Repository with the path of /var/lib/gems/1.8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin could not be found. Exiting

running warehouse under ubuntuserver

**Comment by drcapulet** [comment]
Can you give me a backtrace please?

**Comment by MACRASSI** [comment]
do you mean "rake warehouse:sync --trace"?

*\* Invoke warehouse:sync (first_time)
*\* Execute warehouse:sync
DEPRECATION WARNING: require "activeresource" is deprecated and will be removed in Rails 3. Use require "active_resource" instead.. (called from /var/lib/gems/1.8/gems/activeresource-2.3.5/lib/activeresource.rb:2)
Repository with the path of /var/lib/gems/1.8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin could not be found. Exiting

**Comment by MACRASSI** [comment]
I followed your instructions.

i ran "RAILS_ENV=production"

i ran "rake db:schema:load" without problems

i created a useraccount, logged in and created a repo. then it sayed that the repo needs to be synced.

so i tried so run "rake warehouse:sync" but it gave me that error

---

May be helpfull:

rails -v = Rails 3.0.1
running ubuntuserver

**Comment by drcapulet** [comment]
When you created the repository, what value did you set for it's path?

**Comment by MACRASSI** [comment]
repo path = /home/rasmus/git/projektmanagement/

**Comment by drcapulet** [comment]
Wait are you trying to run this under rails 3? And try running
rake warehouse:sync[/home/rasmus/git/projektmanagement/]

**Comment by MACRASSI** [comment]
Using
rake warehouse:sync[/home/rasmus/git/projektmanagement/]
brings the same error.

Under wich rails version do i have to run it?

**Comment by MACRASSI** [comment]
rake warehouse:sync[/home/rasmus/git/projektmanagement/]

(in /home/rasmus/warehouse)

DEPRECATION WARNING: require "activeresource" is deprecated and will be removed in Rails 3. Use require "active_resource" instead.. (called from /var/lib/gems/1.8/gems/activeresource-2.3.5/lib/activeresource.rb:2)
Repository with the path of /home/rasmus/git/projektmanagement/ could not be found. Exiting

Getting the same error using rails -v = Rails 2.3.5

**Comment by drcapulet** [comment]
Okay try opening up the console and run Repository.first.sync_revisions

**Comment by MACRASSI** [comment]
Sorry, but this is my first time working with rails.
Could you give me a little more detail how to do it?
I have ssh access on my server.

Many thanx for your help

**Comment by drcapulet** [comment]
run 'script/console' and then when it prints out '>>' (or something like that) type in 'Repository.first.sync_revisions' and press enter

**Comment by MACRASSI** [comment]
i get this:

./console

Loading development environment (Rails 2.3.5)
/var/lib/gems/1.8/gems/rails-2.3.5/lib/rails/gem_dependency.rb:119:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
/usr/lib/ruby/1.8/yaml.rb:143:in `initialize':Errno::ENOENT: No such file or directory - config/bitly.yml

> > Repository.first.sync_revisions

NoMethodError: undefined method `sync_revisions' for nil:NilClass
    from /var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/whiny_nil.rb:52:in`method_missing'
    from (irb):1

**Comment by drcapulet** [comment]
oh - instead of 'script/console' run 'script/console production'

**Comment by MACRASSI** [comment]
okay, i tried that but still get an error

 script/console production
Loading production environment (Rails 2.3.5)
/var/lib/gems/1.8/gems/rails-2.3.5/lib/rails/gem_dependency.rb:119:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
Help for hooks isn't done yet. It currently just spits out whatever you pass it.

> > Repository.first.sync_revisions
> > /home/rasmus/warehouse/lib/warehouse/hooks.rb:39: warning: already initialized constant BITLY_API_LOGIN
> > /home/rasmus/warehouse/lib/warehouse/hooks.rb:40: warning: already initialized constant BITLY_API_KEY
> > ./app/models/hook.rb:2: warning: already initialized constant WH_HOOKS
> > ./app/models/hook.rb:3: warning: already initialized constant ALL_HOOKS
> > NameError: uninitialized constant Warehouse::Syncer::LOGGER
> >     from /var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:105:in `const_missing'
> >     from /home/rasmus/warehouse/lib/warehouse/syncer.rb:62:in`process'
> >     from /home/rasmus/warehouse/lib/warehouse/syncer.rb:55:in `process'
> >     from /home/rasmus/warehouse/app/models/repository.rb:26:in`sync_revisions'
> >     from (irb):1

**Comment by drcapulet** [comment]
I'll have to look into that error, but in your config/warehouse.yml file, add

  log_syncer: true
To the end of it. Then try that again.

**Comment by MACRASSI** [comment]
Thanx!
After adding "log_syncer: true" to "config/warehouse.yml" it works!
